- README.md
> add Cypress dashboard badge

- app/commands/traversal.html
> Update display code for prev example

- CONTRIBUTING.md
- README.md
- package.json
outline how to deploy kitchen-sink
> Add contributing doc to explain deploy process for kitchensink

- app/commands/local-storage.html
> fix broken link

- app/commands/aliasing.html
- formatting issue on mobile devices (long line requiring horizontal scroll)
- tweak comments
PS. The kitchensink examples are very handy as a quick reference!
> Formatting issue on mobile devices + tweak comments

- app/commands/traversal.html
- cypress/integration/examples/traversal.spec.js
The test for prevUntil now has an assertion, documentation is updated to reflect the content of the test
> added assertion to prevUntil test (#65)

- README.md
- renovate.json
> add renovate app badge, config file, close #72

- package-lock.json
update package-lock.json for renovate
in the future renovate should do this automatically
> update package-lock.json for renovate deps

- .npmrc
- circle.yml
- cypress/integration/examples/assertions.spec.js
- cypress/integration/examples/cypress_api.spec.js
- cypress/integration/examples/local_storage.spec.js
- cypress/integration/examples/navigation.spec.js
- cypress/integration/examples/spies_stubs_clocks.spec.js
- cypress/integration/examples/utilities.spec.js
- package-lock.json
- package.json
- tsconfig.json
> Type check specs 71

- .gitignore
- cypress/integration/examples/cypress_api.spec.js
- update gitignore
- close #86
> remove unusual use of whitelist callback + assertion

- appveyor.yml
just to see Travis environment variables from a forked PR
> chore: example empty pull request from forked repo

- .gitlab-ci.yml
- README.md
> Gitlab fixes 105

- README.md
- basic/Jenkinsfile
- basic/README.md
- basic/circle.yml
> start with basic config files for #116

- .travis.yml
- README.md
- basic/.travis.yml
- basic/README.md
Also reorder CIs by name (in the first column)
> Add basic travis CI example

- .gitlab-ci.yml
- README.md
- basic/.gitlab-ci.yml
- basic/README.md
> add basic gitlab CI config example for #127

- app/assets/js/scripts.js
- app/commands/files.html
- app/commands/network-requests.html
- app/utilities.html
- cypress/integration/examples/files.spec.js
- cypress/integration/examples/network_requests.spec.js
- cypress/integration/examples/utilities.spec.js
> point at jsonplaceholder.cypress.io, close #112

- .gitlab-ci.yml
- basic/.gitlab-ci.yml
> use env variable over hardcoded path

- .vscode/settings.json
- app.json
- package-lock.json
- package.json
- scripts/set-port.js
> add command to use dynamic port before running tests

- app/commands/actions.html
gets rid of warning security messages in console
> Update img placeholder url to HTTPS

- app/index.html
> fix: links to file commands on main page

- CONTRIBUTING.md
- circle.yml
- package-lock.json
- package.json
- remove our releaser and just use semantic release on Circle
- closes #167
> chore: use semantic release to publish to NPM

- app/assets/css/styles.css
- app/commands/querying.html
- cypress/integration/examples/querying.spec.js
> feat: add data attribute example to cy.get

- .vscode/settings.json
- app/commands/assertions.html
- cypress/integration/examples/assertions.spec.js
I always wonder how to match text of an element, these are examples
> feat: add more examples for text matching

- README.md
- circle.yml
- package.json
> Move mac to circle 222

- app/commands/files.html
- cypress/integration/examples/files.spec.js
shows how to use "this" with fixture and how to require JSON fixture for simplicity
> add require and fixture example

- .semaphore/semaphore.yml
- README.md
- package.json
> Semaphore2

- .semaphore/semaphore.yml
- README.md
- basic/.semaphore.yml
- closes #266 
- both basic and parallel configs
> Add Semaphore v2 CI example 266

- app/commands/spies-stubs-clocks.html
- cypress/integration/examples/spies_stubs_clocks.spec.js
Also relevant: https://github.com/cypress-io/cypress/issues/3512
> feat: add example how spy retries following assertions

- app/commands/connectors.html
- cypress/integration/examples/connectors.spec.js
Explaining the returned value vs value yielded by the last command
> add more .then examples

- README.md
- amplify.yml
> Amplify console config

- app.json
- cypress/plugins/index.js
- package-lock.json
- package.json
- patches/cypress+3.5.0.patch
- always pass "no-sandbox" Electron flag via a patched Cypress
> Fix Heroku pipeline build for Cypress 3.5.0

- app/assets/css/styles.css
- app/assets/js/scripts.js
- app/commands/actions.html
- cypress/integration/examples/actions.spec.js
- close https://github.com/cypress-io/cypress-example-kitchensink/pull/298
> Add .rightclick to kitchensink

- app/index.html
- forgot to add rightclick to index page including all commands.
> fix: add rightclick to main index page

- azure-ci.yml
- basic/azure-ci.yml
- closes #132 
Added NPM and Cypress binary caching
> Add caching to Azure ci example

- .semaphore/semaphore.yml
Simple config using `parallelism: 3`
> Use parallelism parameter on Semaphore

- .github/workflows/checks.yml
Introducing GitHub Action which statically analyzes current project tests and provides a brief summary:
* Tests added by this Pull Request
* Tests removed by this Pull Request
* Tests skipped by this Pull Request
* Lists all tests in this project
* Adds label 'has tests' if PR contains tests
* Fails when finding `.only` exclusive tests
Read more about it here: https://github.com/testomatio/check-tests
Demo how it works on my fork: https://github.com/DavertMik/cypress-example-kitchensink/pull/1#issuecomment-568568483
Looks like this action was not added to checks, so let me show how a summary for this PR should look like:
---
🌀 Tests overview by [Testomatio](https://testomat.io)
Found **114** cypress tests in 19 files 
No new tests added or removed
<details>
<summary>📑 List all …
> GitHub Action that statically analyzes project tests

- app/commands/actions.html
- cypress/integration/examples/actions.spec.js
- closes #23
- examples of single and multiple selections
> feat: add select assertions

- app/commands/network-requests.html
- cypress/integration/examples/network_requests.spec.js
> update flaky network test

- circle.yml
- cypress/integration/examples/network_requests.spec.js
new version of orb set the cache path
> use orb 1.14.0 and remove duplicate line

- amplify.yml
> Update amplify.yml to not pin version of mocha

- app/commands/assertions.html
- cypress/integration/examples/assertions.spec.js
- for documentation update on retry-ability https://github.com/cypress-io/cypress-documentation/pull/2548
> add an example using should cb

- cypress/integration/examples/misc.spec.js
- shippable.yml
it fails trying to do apt-update, maybe we don't need to do anything special
> Try to fix Shippable

- netlify.toml
- package-lock.json
- package.json
Use our plugin to test Netlify builds before deploying
> Use cypress netlify plugin

- app/commands/cookies.html
Changed clearCookies to clearCookie on line 146
> Fixed typo for issue #389

- .github/workflows/parallel.yml
- app/commands/spies-stubs-clocks.html
- app/commands/waiting.html
just a couple of anchors and a few more links to the `cy.wait` page that was really really empty
> add more anchors

- netlify.toml
- package-lock.json
- package.json
Netlify build and test completed successfully
https://app.netlify.com/sites/netlify-cypress/deploys/5ed99cf8e0f2c9e7eefd515b
> Update dependency netlify-plugin-cypress to v1.3.11

- app/commands/files.html
- app/commands/network-requests.html
- cypress/integration/examples/files.spec.js
- cypress/integration/examples/network_requests.spec.js
https://github.com/cypress-io/cypress/pull/9280
> changes for automatically parse JSON req/res bodies

- .circleci/config.yml
- .github/workflows/checks.yml
- .github/workflows/chrome-80.yml
- .github/workflows/chrome-docker.yml
- .github/workflows/chrome-headless.yml
- .github/workflows/chrome.yml
- .github/workflows/parallel.yml
- .github/workflows/single.yml
- .github/workflows/using-action.yml
- package-lock.json
- package.json
- shippable.yml
Cypress v5 -> v6
GH Action v1 -> v2
update Shippable config
> upgrade to Cypress v6 and fix GitHub actions

- .semaphore/semaphore.yml
- .travis.yml
- netlify.toml
- package-lock.json
- package.json
Testing new preview version of Netlify plugin 
https://github.com/cypress-io/netlify-plugin-cypress/pull/133
> bump Netlify to v2 preview

- cypress/integration/examples/local_storage.spec.js
Comments matching statements were in the wrong place
> Update localstorage.spec.js line comments

- app/assets/css/todo.css
Fixes an issue originally reported here - https://github.com/cypress-io/cypress/pull/15826#issuecomment-848750452, also partially quoted below
I tracked down the cause of this issue to be special characters that are not supported by the default fonts (and thus require the loading mentioned in the error). I replaced the character that was causing the error with another that creates only a minor visual change and does not cause the error.
> I have another note on the new scaffolding that I just found. For the new `todo` spec, if you run it via `cypress run` on a Mac in Electron (headless and headed) - it exhibits this issue cypress-io/cypress#7245, where it prints `Cypress Helper (Renderer)[2978:18327] CoreText note:` messages to stdout.
> 
> 
> <img alt="Screen Shot 2021-05-26 at 7 53 41 …
> Fix electron font warning for todo spec

- README.md
- app/commands/actions.html
> fix: locators rightclick() test on the example pages was changed

- cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js
Referenced PR has already been completed.
> chore: remove comment from spies_stubs_clocks.cy.js

- basic/README.md
Fixes errors and omissions in [basic/README.md](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/basic/README.md).
> docs: update contents of basic/readme

- .eslintrc
This PR is an enhancement to the CI process of the repository. It adds [`eslint:recommended`](https://eslint.org/docs/latest/rules/) to the set of rules which are checked.
The [.eslintrc](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.eslintrc) ESLint configuration file has the following configuration options added:
```json
"extends": [
"eslint:recommended"
],
"env": {
"node": true
},
```
No code changes are necessary to the examples. They already comply with [`eslint:recommended`](https://eslint.org/docs/latest/rules/).
Linting against the set of rules defined by [`eslint:recommended`](https://eslint.org/docs/latest/rules/) ensures that the Cypress examples adhere to a documented set of industry standard rules. This retains the on-going quality of the examples …
> ci: add eslint:recommended

- .circleci/config.yml
This should fix the Chromedriver errors in our build.
> chore: Bump circleci orb

- .circleci/config.yml
Close https://github.com/cypress-io/cypress-example-kitchensink/issues/799
> chore: bump cypress orb to fix 404s of chrome in our tests

- README.md
Preview
https://github.com/MikeMcC399/cypress-example-kitchensink/blob/fix/readme-links/README.md
> docs: fix readme links reported by link checker

- .circleci/config.yml
- package-lock.json
- package.json
updates the kitchensink to use Cypress 14
> chore: update to Cypress 14

- package-lock.json
- package.json
A new major version `5.x` of [@stylistic/eslint-plugin](https://www.npmjs.com/package/@stylistic/eslint-plugin) is now available.
- Update all ESLint related packages to their latest versions:
| Package                                                                            | From                                                                              | To                                                                                |
| ---------------------------------------------------------------------------------- | --------------------------------------------------------------------------------- | --------------------------------------------------------------------------------- |
| [eslint](https://www.npmjs.com/package/eslint)                                     | …
> chore(deps): update ESLint related deps to latest
