.npmrc, appveyor.yml, package.json
Avoid manually stopping process which breaks on Windows by using `npm-run-all` utility with `--race` flag
https://github.com/mysticatea/npm-run-all/blob/master/docs/run-p.md
=> use npm-run-all parallel run to stop server

cypress/integration/example_spec.js, package.json
This is example test that shows badly formatted text in the reporter.
```js
it('expect shape of an object', function(){
const person = {
name: 'Joe',
age: 20
}
expect(person).to.have.all.keys('name', 'age')
})
```
=> add example test for have.all.keys

README.md
As the `example_spec.js` file has been split the link redirect to the directory where all the tests has been split up
=> fix(doc): fix 404 link

README.md
I've updated the README.md with the command on how to run cypress.
It took me a couple minutes scrolling through the provided link to figure out how to start the test runner.
=> added launch test runner command to README.md

README.md, circle.yml, cypress/integration/examples/cypress_api.spec.js, cypress/integration/examples/misc.spec.js, package-lock.json, package.json
- I wanted something to show https://docs.cypress.io/api/cypress-api/spec.html
- added `start-server-and-test` to simplify local work
- added husky git hooks and `stop-only` to catch stray `.only`
=> add start-server-and-test for simpler local work, Cypress.spec example

app/commands/assertions.html, cypress/integration/examples/assertions.spec.js
- closes #164 for https://github.com/cypress-io/cypress-documentation/issues/1267
`.should(cb)` needs more examples because that is the one assertion people should be writing when our built-in assertions are not enough
=> more assertion examples

app/commands/assertions.html, cypress/integration/examples/assertions.spec.js
for https://github.com/cypress-io/cypress-documentation/issues/1300
=> feat: show how to compare text from two elements

app/commands/querying.html, cypress/integration/examples/querying.spec.js
based on Twitter question
https://twitter.com/LCainsWebDev/status/1086222956349542400
=> More examples getting attributes

cypress/support/commands.js
Minor typo fix for the scaffolded command.js.
Related to: https://github.com/cypress-io/cypress/pull/3677
=> fix typo in scaffolded command.js

app/utilities.html, cypress/integration/examples/utilities.spec.js
Prompted by the stackoverflow and gitter question
https://stackoverflow.com/questions/55272549/compare-datetime-function-cypress
=> chore: add another Moment example

shippable.yml
- closes #251 
Trying to fix display crashing on Shippable by using our Docker image.
Hitting a problem
```
'/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)' to be empty
```
inside `cy.exec` test https://app.shippable.com/github/cypress-io/cypress-example-kitchensink/runs/753/1/console
=> Upgrade libnss3 library on Shippable CI to support Cypress v3.3.0

basic/.gitlab-ci.yml
This allows for better analysis should the cypress tests fail.
=> Add artifacts to test stage

.semaphore/semaphore.yml, basic/.semaphore.yml
- removed Docker image, using standard Linux container
- simpler caching
- removed unnecessary custom build id, since Cypress understands Semaphore env variables
- updated basic example
- inspired by #288
=> Update Semaphore v2 example

README.md
Utilize https://link.cypress.io/kitchensink-amplify-oneclick as the new Amplify button link.
=> Replace Amplify one-click link with alias link

cypress/integration/examples/files.spec.js
Change “read a files contents” to “read file contents”.
=> Fix grammar: a files contents -> file contents

.github/workflows/parallel.yml, .github/workflows/single.yml, .github/workflows/using-action.yml
Added example with single and parallel tests using new version of Cypress.io GitHub Action https://github.com/cypress-io/github-action
I say we start using Cypress GitHub Action and then figure out how to show it in our table of CIs (since we also have "normal" GitHub Action examples without our Cypress Action)
Good to go - the failures are flake
=> Use Cypress GitHub action

package-lock.json, package.json
Gitlab added `extends` job key, which is easier to understand and read then YAML anchors.
https://docs.gitlab.com/ee/ci/yaml/#extends
=> chore: updated gitlab template using extends key

amplify.yml
See https://github.com/aws-amplify/amplify-console/issues/352 for explanation of the issue.
This fixes the `mochawesome-merge` command after 4.0.0 broke the CLI api.
=> Fix mochawesome-merge command after breaking change in v4.0.0

cypress/integration/examples/actions.spec.js, cypress/integration/examples/aliasing.spec.js, cypress/integration/examples/assertions.spec.js, cypress/integration/examples/connectors.spec.js, cypress/integration/examples/cookies.spec.js, cypress/integration/examples/cypress_api.spec.js, cypress/integration/examples/files.spec.js, cypress/integration/examples/local_storage.spec.js, cypress/integration/examples/location.spec.js, cypress/integration/examples/misc.spec.js, cypress/integration/examples/navigation.spec.js, cypress/integration/examples/network_requests.spec.js, cypress/integration/examples/querying.spec.js, cypress/integration/examples/spies_stubs_clocks.spec.js, cypress/integration/examples/traversal.spec.js, cypress/integration/examples/utilities.spec.js, cypress/integration/examples/viewport.spec.js, cypress/integration/examples/waiting.spec.js, cypress/integration/examples/window.spec.js, cypress/plugins/index.js
- add JSDoc to plugins file for type-completions for `on(...)` events and `config`
- lowercase reference types
=> Add jsdoc pluginsfile

circle.yml, cypress/integration/examples/network_requests.spec.js
Updated network test to be slightly more robust, was getting 501 vs 500 items
=> Demo ff on circle

azure-ci.yml
These rows in conjunction got me confused for a while:
As an unexperienced Cypress user, I assumed the RECORD_KEY was supposed to be my BUILDNUMBER.
This is clearly not the case, since the following error will be produced:
> Errors: [ "data.recordKey must be uuid format" ]
My change should suffice to clarify that doubt, but I'm sure you as domain experts can improve it as well.
=> Clarify comments in azure-ci.yml

cypress/integration/examples/misc.spec.js
fix usage of `Cypress.Screenshot.defaults()`
- tests will fail since Cypress typedefs are incorrect
=> fix: Screenshot.defaults usage

.buildkite/pipeline.yml
Buildkite [command steps](https://buildkite.com/docs/pipelines/command-step) can and often do happen across multiple [agents](https://buildkite.com/docs/agent/v3) (usually on different hosts), so work to prepare and then run a command should be done within a single step. This also adds some [log output grouping](https://buildkite.com/docs/pipelines/managing-log-output) and uses shell escaping so that paths with spaces won't break.
I don't have Cypress set up enough to get a passing build, but here's what it looks like:
=> update Buildkite pipeline

.circleci/config.yml
Note: temporarily disable dependency to publish the new NPM version if install works on `master`
=> split install and lint jobs

app/index.html, app/utilities.html, cypress/integration/examples/utilities.spec.js, shippable.yml
This removes deprecated `Cypress.moment()` from the scaffolded examples. 
I don’t *really* feel like this has to go out with 7.0.0 (where `Cypress.moment()` will be removed completely). It’s already deprecated so I think it’s ok to remove from the master example.
=> feat: Remove Cypress.moment() usage from examples

README.md, basic/buildspec.yml, buildspec.yml
Defines a basic and parallel example for using AWS CodeBuild.
The parallel config uses the newly released batched feature of AWS CodeBuild using the $CODEBUILD_INITIATOR as it provides the entity that started the build which is unique and can be used as the `--ci-build-id` for the Cypress Dashboard (e.g. `awsCodeBuild-cypress-kitchen-sink/AWSCodeBuild-a14fc8e3-b5d6-42f9-9067-345d48a8f0fd`)
- https://aws.amazon.com/about-aws/whats-new/2020/07/aws-codebuild-now-supports-parallel-and-coordinated-executions-of-a-build-project/
- https://docs.aws.amazon.com/codebuild/latest/userguide/batch-build-buildspec.html
=> Add AWS CodeBuild Basic and Parallel config file examples

.circleci/config.yml, appveyor.yml
- closes #474 by recording Circle Windows runs
- closes #438 and enabled Windows AppVeyor Firefox tests
Flakey test failures: https://github.com/cypress-io/cypress-example-kitchensink/issues/476 for FF on Windows, and Chrome on AppVeyor with very slow actions spec that fails on `click({ multiple: true })`
=> enable appveyor firefox testing

cypress/plugins/index.js
Reverts some changes to the plugin file that would have made their way into scaffolding and not provided the user with an empty plugins file
=> fix: remove window size changes from plugin file 

cypress/integration/2-advanced-examples/files.spec.js
Address https://github.com/cypress-io/cypress/issues/16785
`cy.wrap()` accepts a `subject` and `options` arguments - not a string as a second arg. 
Remove erroneous second string arg from example.
=> Remove second arg from cy.wrap

package-lock.json, package.json
Follow up to #503, removing the no-longer-used TypeScript dependency and scripts using it.
=> Remove TypeScript dependency and scripts

.github/workflows/semantic-pull-request.yml
Attempting to set up enforcement of semantic PR names, same as we have in the main cypress repo. File is an exact copy of https://github.com/cypress-io/cypress/blob/develop/.github/workflows/semantic-pull-request.yml.
=> fix: Add semantic-pull-request checking

cypress.config.js
This PR is part of https://github.com/cypress-io/cypress/pull/22000 which close https://github.com/cypress-io/cypress/issues/21909
The idea is to have `e2e` or `component` property set on the config file to run the project in run mode - otherwise throw the correct error message
=> feat: Add e2e property to config

app/cypress-api.html, cypress/e2e/2-advanced-examples/cypress_api.cy.js
`Cypress.Cookies.defaults` and `Cypress.Cookies.preserveOnce` were deprecated in Cypress version 9.7.0 and are being completely removed in Cypress version 11.0.0. The functionality has been replaced with `cy.session`.
=> chore: Remove deprecated Cookies.defaults/preserveOnce

README.md
Hi all,
The reference to the tests files directory leads to a 404 error page. This PR just updates the path from `cypress/integration` to `cypress/e2e`.
Best,
Hendrik
=> chore: Fix link to test examples in README.md

cypress/e2e/2-advanced-examples/connectors.cy.js
Related monorepo PR: https://github.com/cypress-io/cypress/pull/25296
Basically, .should() will no longer break query chains. So in this example, 
```
cy.get('.connectors-div')
.should('be.hidden') // This assertion
.invoke('show')
.should('be.visible') // And this assertion can never be true on the same subject at the same time.
```
=> fix: .should() new behavior

.circleci/config.yml
This PR refactors CI to use the CircleCI Orb `v3`
=> chore: use circleci orb 3

package-lock.json, package.json
This PR removes the unused npm package [stop-build](https://www.npmjs.com/package/stop-build) which invokes critical vulnerabilities in `npm audit` through `minimist@0.0.10` and `lodash@3.10.1`. The package was last updated 6 years ago and it appears to be unmaintainable due to its own dependencies (see https://github.com/bahmutov/stop-build/issues/3).
After this change `npm audit` reports:
`41 vulnerabilities (1 low, 7 moderate, 33 high)`
=> chore(deps): uninstall unused stop-build

.github/workflows/checks.yml, .github/workflows/chrome-headless.yml, .github/workflows/chrome.yml, .github/workflows/parallel.yml, .github/workflows/single.yml, .github/workflows/using-action.yml, README.md
This PR updates workflows in [.github/workflows](https://github.com/cypress-io/cypress-example-kitchensink/tree/master/.github/workflows) which are currently specifying `ubuntu-18.04`.
According to [ubuntu-18.04 README](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu1804-Readme.md) this version is deprecated and will be fully unsupported by April 1, 2023.
The affected workflows are updated to use [ubuntu-22.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md) instead, which is currently equivalent to `ubuntu-latest`.
=> chore(deps): use ubuntu-22.04 in gh workflows

README.md
This PR removes the obsolete CI provider "Shippable" from being displayed in [README.md](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md). No CI results can be displayed from "Shippable" since it is no longer operating.
The former CI provider "Shippable" no longer provides a service.
- https://app.shippable.com/github/cypress-io/cypress-example-kitchensink is no longer reachable.
- http://docs.shippable.com/ is no longer reachable.
- The badge `[![Shippable CI](https://api.shippable.com/projects/56c38fdc1895ca4474743010/badge?branch=master)](https://app.shippable.com/github/cypress-io/cypress-example-kitchensink)` no longer responds.
- Shippable's GitHub repositories under https://github.com/Shippable have not been updated since September 2021.
- See [We’ve …
=> fix: remove unreachable CI provider "Shippable"

.circleci/config.yml
- Closes #606 
This [job](https://app.circleci.com/pipelines/github/cypress-io/cypress-example-kitchensink/1279/workflows/16d803e2-23ea-4d29-af95-3cfd104d1a68/jobs/8671) demonstrates this working with `--dry-run`.
=> chore: fix releases

.github/workflows/checks.yml
This PR fixes the workflow [.github/workflows/checks.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/checks.yml) which currently is looking in the wrong place for Cypress tests due to migration to Cypress 10.
The workflow [.github/workflows/checks.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/checks.yml) finds no tests:
```test
Run testomatio/check-tests@stable
with:
framework: cypress
tests: ./cypress/integration/**/**.spec.js
token: ***
has-tests-label: true
Using default branch master
Added 0 tests, removed 0 tests
Total 0 tests
```
The workflow is looking in the directory for a Cypress legacy configuration. This was changed through PR https://github.com/cypress-io/cypress-example-kitchensink/pul …
=> fix: migrate test checks to cypress 10+ location

appveyor.yml
This PR updates the CI workflow [appveyor.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/appveyor.yml) from Node.js 12 to Node.js 18. The [Node.js release schedule](https://github.com/nodejs/release#release-schedule) shows that Node.js 12 already entered its end-of-life phase one year ago on April 30, 2022.
Verify by inspection of
https://ci.appveyor.com/project/cypress-io/cypress-example-kitchensink
=> chore(deps): update appveyor to node.js 18

app.json
This PR updates the [Heroku CI: app.json](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/basic/app.json) workflow to a supported version of Ubuntu.
The workflow is currently configured to use
`"stack": "cedar-14"` 
which selects Ubuntu 14.04 LTS. This stack entered (a postponed) [end-of-life](https://devcenter.heroku.com/changelog-items/1603) more than 2 years ago on November 2, 2020.
The `stack` is updated by this PR to 
`heroku-22`
as listed in [Upgrading to the Latest Stack](https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack). This corresponds to Ubuntu 22.04 LTS.
This example is not automatically verifiable. There is no build status listed in the [README: CI Status](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md#c …
=> chore(deps): update Heroku CI to heroku-22

.github/workflows/chrome-docker.yml
This PR updates the CI example [.github/workflows/chrome-docker.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/chrome-docker.yml).
1. It binds the workflow to `ubuntu-22.04` instead of `ubuntu-latest` in alignment with other workflows contained in the [.github/workflows](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows) directory.
2. It updates the Docker container from
- [cypress/browsers:node14.17.6-chrome100-ff98](https://hub.docker.com/layers/cypress/browsers/node14.17.6-chrome100-ff98/images/sha256-3f1ceb98712c697071ac194a0cae263a8b082af8ed418b7792dd9b0888a0338f) to
- [cypress/browsers:node18.12.0-chrome107](https://hub.docker.com/layers/cypress/browsers/node18.12.0-chrome107/images/sha256-50959d1166a …
=> chore(deps): update CI Chrome Docker example to Docker Node.js 18

package-lock.json, package.json
This PR updates the npm module [netlify-plugin-cypress](https://www.npmjs.com/package/netlify-plugin-cypress) to [v2.2.1](https://github.com/cypress-io/netlify-plugin-cypress/releases/tag/v2.2.1) which updates also the dependency [puppeteer](https://www.npmjs.com/package/puppeteer) to [18.1.0](https://github.com/puppeteer/puppeteer/releases/tag/v18.1.0).
- This follows on from PR https://github.com/cypress-io/netlify-plugin-cypress/pull/320 to resolve an issue supporting Apple Silicon/M1.
- It supersedes the stale PR https://github.com/cypress-io/cypress-example-kitchensink/pull/535
=> fix(deps): update netlify-plugin to 2.2.1

.github/workflows/parallel.yml, .github/workflows/single.yml
This PR updates the CI examples
- [.github/workflows/single.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/single.yml)
- [.github/workflows/parallel.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/parallel.yml)
to use Node.js 18 instead of Node.js 14 (which has its [end-of-life transition](https://github.com/nodejs/release#release-schedule) in 3 weeks on April 30, 2023).
- Links have been updated.
- Dashboard is renamed to Cypress Cloud in comments.
- The link to outdated (2019) contents in http://www.thedreaming.org/2019/09/10/github-ci/ is removed and replaced by a reference to [.github/workflows/using-action.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflo …
=> chore(deps): update CI GitHub single and parallel to Node.js 18

package-lock.json, package.json
This PR updates the npm module [start-server-and-test](https://www.npmjs.com/package/start-server-and-test) to [v2.0.0](https://github.com/bahmutov/start-server-and-test/releases/tag/v2.0.0). This significantly reduces the number of deprecation warnings when executing `npm install`.
---
BEFORE
```text
$ npm install
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/pinpoint@1.0.2: Moved to 'npm install @sideway/pinpoint'
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or …
```
=> chore(deps): update start-server-and-test to 2.0.0

scripts/set-port.js
This PR restores [scripts/set-port.js](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/scripts/set-port.js) to a working condition after the migration of examples from `cypress/integration` to [cypress/e2e](https://github.com/cypress-io/cypress-example-kitchensink/tree/master/cypress/e2e) in PR #528.
[scripts/set-port.js](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/scripts/set-port.js) is only used by the workflow [app.json](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/app.json) which is a documentation-only example for the [Heroku CI](https://devcenter.heroku.com/articles/heroku-ci) provider. The workflow calls it through `npm run ci:set-port`
Since this is not a live example and there is no status badge, the issue …
=> fix: restore set-port.js to work in Cypress 10+ environment

.gitlab-ci.yml, Dockerfile, Jenkinsfile, basic/.circleci/config.yml, basic/.gitlab-ci.yml, basic/Jenkinsfile, basic/codeship-pro/Dockerfile, buddy.yml
This PR updates each of the CI examples that were previously using the outdated Docker containers with Node.js versions 10 and 12, which already reached their respective [end-of-life](https://github.com/nodejs/release#release-schedule) on April 30, 2021 and April 30, 2022:
- `cypress/base:10`
- `cypress/base:latest`
The following examples are changed to use [cypress/base:18.14.1](https://hub.docker.com/layers/cypress/base/18.14.1/images/sha256-a63a2bec81efa794970664ad24466c1627138b8668d37f6cd22fd71f6080caad)
CI | Build status | basic config file | full parallel config
:--- | :--- | :--- | :---
[Buddy](https://buddy.works/docs) | - | [buddy.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/buddy.yml)
[CircleCI](https://circleci.com/docs/) | …
=> chore(deps): update CI Docker usage to cypress/base:18.14.1

package-lock.json, package.json
This PR updates the npm package [globby](https://www.npmjs.com/package/globby) from `globby@9.1.0` to `globby@version11` [v11.1.0](https://github.com/sindresorhus/globby/releases/tag/v11.1.0).
This removes some deprecation warnings output by executing `npm install`:
---
BEFORE
```text
$ npm install
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when …
```
=> chore(deps): update globby to 11.1.0

README.md
This PR is related to issue https://github.com/cypress-io/cypress-example-kitchensink/issues/615. It removes the failing status badge for GitLab CI from the [CI Status table](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md#ci-status).
According to https://github.com/cypress-io/cypress-example-kitchensink/issues/615#issuecomment-1498196714 from @emilyrohrbough, it is planned to archive the GitLab mirror copy repository https://gitlab.com/cypress-io/cypress-example-kitchensink/ so this will disable any CI workflows.
The links to GitLab CI workflows can remain. They may be useful as templates for users of GitLab CI even if they are not live. More than half of the examples in this table are documentation-only examples which do not demonstrate any live CI run …
=> docs: remove GitLab CI status badge

README.md
This PR resolves https://github.com/cypress-io/cypress-example-kitchensink/issues/602. It removes the failing status badge for Travis CI from the [CI Status table](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md#ci-status).
The links to Travis CI workflows can remain. They may be useful as templates for users of Travis CI who have migrated to the subscription service. More than half of the examples in this table are documentation-only examples which do not demonstrate any live CI run and status, so leaving the Travis CI workflows in the table would fit into this structure.
=> docs: remove Travis CI status badge

.husky/pre-commit, .husky/pre-push, package-lock.json, package.json, scripts/prepare.js
This PR updates [husky](https://www.npmjs.com/package/husky) from the 4 year old `1.3.1` version to the latest version [husky v8.0.3](https://github.com/typicode/husky/releases/tag/v8.0.3). This aligns it better with the `7.0.2` version used by [cypress-io/cypress](https://github.com/cypress-io/cypress).
The scripts are migrated according to the documentation [Migrate from v4 to v8](https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v8).
[husky v8.0.3](https://github.com/typicode/husky/releases/tag/v8.0.3) supports `node >=14`.
Husky documentation [Disable husky in CI/Docker/Prod](https://typicode.github.io/husky/#/?id=disable-husky-in-cidockerprod) was also used to mitigate a conflict arising in [.github/workflows/chrome-docker.yml](https://github.com/cypress-io/cypress-example-kit …
=> chore(deps): update husky to 8.0.3

.gitignore
This PR adds the `cypress/downloads` directory to [.gitignore](https://github.com/cypress-io/github-action/blob/master/.gitignore). See Cypress documentation [Configuration: Folders/Files](https://docs.cypress.io/guides/references/configuration#Folders--Files).
This is a temporary directory and its contents should not be committed to git.
=> chore: add cypress/downloads to .gitignore

package.json
This PR removes the `v1` Husky hooks located in [package.json](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/package.json). These were replaced by [.husky/pre-commit](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.husky/pre-commit) through PR https://github.com/cypress-io/cypress-example-kitchensink/pull/626.
The `v1` Husky hooks are unused by Husky `v8`.
See Husky documentation [Migrate from v4 to v8](https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v8).
=> chore: remove husky hooks from package.json

package-lock.json, package.json
This PR updates the npm module [yaml-lint](https://www.npmjs.com/package/yaml-lint) to the latest version (`1.7.0`). It resolves 2 high vulnerabilities reported by `npm audit`.
Execute
```bash
npm ci
npm run lint:yaml
```
and confirm success as follows:
```text
√ YAML Lint successful.
```
=> chore(deps): update yaml-lint to 1.7.0

package-lock.json, package.json, scripts/start.js
This PR bumps the version of npm module [serve](https://www.npmjs.com/package/serve) from `11.3.2` to [14.2.0](https://github.com/vercel/serve/releases/tag/14.2.0).
It resolves 4 vulnerabilities (3 high and 1 moderate).
The following option (see `npx serve --help`) is used:
```text
-L, --no-request-logging            Do not log any request information to the console.
```
to suppress verbose logging, which otherwise fills up the logs.
```bash
npm ci
npm run local:run
```
1. The tests should be successful.
2. There should be no verbose logging.
3. The information text "UPDATE AVAILABLE The latest version of `serve` is 14.2.0" should **not** appear.
=> chore(deps): update serve to 14.2.0

.circleci/config.yml, package-lock.json, package.json
This PR updates from `semantic-release@15.13.32` to [semantic-release@19.0.3](https://github.com/semantic-release/semantic-release/releases/tag/v19.0.3) which aligns to the same version used by [cypress-io/cypress](https://github.com/cypress-io/cypress). It resolves 31 vulnerabilities (7 moderate and 24 high) reported by `npm audit`.
Examine CircleCI workflow report on https://app.circleci.com/pipelines/github/cypress-io/cypress-example-kitchensink?branch=master
Look for workflow: `linux-build` job: `release` and check that it was successfully executed.
Example using current `15.13.32`:
=> ci(deps): update semantic-release to 19.0.3

README.md
This PR removes the CI status badge for Semaphore V2 in the [README: CI Status](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md#ci-status). The CI for Semaphore has not been active for the last 4 years.
The badge was linked to https://cypress-io.semaphoreci.com/projects/cypress-example-kitchensink which shows a status from Aug 7, 2019.
The name of the CI provider is changed from "Semaphore v2" to [Semaphore 2.0](https://docs.semaphoreci.com/) which corresponds to the naming used on their documentation site.
=> docs: remove Semaphore CI status badge

.eslintrc, cypress/e2e/2-advanced-examples/cypress_api.cy.js, cypress/e2e/2-advanced-examples/files.cy.js, package-lock.json, package.json
This PR resolves https://github.com/cypress-io/cypress-example-kitchensink/issues/629 "mocha lint errors on example tests with eslint-plugin-mocha 10.1.0".
[eslint-plugin-mocha](https://www.npmjs.com/package/eslint-plugin-mocha) is updated to latest ([10.1.0](https://github.com/lo1tuma/eslint-plugin-mocha/releases/tag/10.1.0))
- Ignore use of arrow function syntax `() =>` using `"mocha/no-mocha-arrows": "off"` rule in `.eslintrc` configuration.
- In [cypress/e2e/2-advanced-examples/files.cy.js](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/cypress/e2e/2-advanced-examples/files.cy.js) two instances of `beforeEach` are merged into one instance to fix `mocha/no-sibling-hooks`.
- In [cypress/e2e/2-advanced-examples/cypress_api.cy.js](https://github.com/cypress-io/cypres …
=> feat: update example tests for compatibility with latest recommended mocha lint

.github/workflows/parallel.yml, .github/workflows/single.yml
- This PR resolves https://github.com/cypress-io/cypress-example-kitchensink/issues/645.
- It keys the Cypress [Linux binary cache](https://docs.cypress.io/guides/references/advanced-installation#Binary-cache) located at `~/.cache/Cypress` on `package-lock.json` instead of `package.json`.
- Since it is possible to update the installed Cypress version by changing only `package-lock.json`, as in renovate's PR https://github.com/cypress-io/cypress-example-kitchensink/pull/640, the workflows listed below need to start a new cache in this case.
It modifies the following two GitHub action workflows:
- [.github/workflows/parallel.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/parallel.yml) and
- …
=> fix: hash workflow cache on package-lock

package-lock.json, package.json
This PR installs Cypress as an exact version `12.10.0`, replacing the current semantic version selection `^12.1.0`
```bash
npm install cypress@latest -D -E
```
was used.
- It works around the issue https://github.com/cypress-io/cypress-example-kitchensink/issues/645
- It prepares Cypress better for automatic updates by `renovate` 
- It has the advantage that manually viewing [package.json](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/package.json) shows the exact version in use
=> chore(deps): install Cypress 12.10.0 exact version

README.md
This PR replaces the link in the README section [Help + Testing](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md#help--testing)
* [Gitter Chat](https://gitter.im/cypress-io/cypress)
by
* [Discord Chat](https://on.cypress.io/discord)
=> docs: refer to Discord chat not Gitter

package-lock.json, package.json
This PR updates [eslint-plugin-cypress](https://www.npmjs.com/package/eslint-plugin-cypress) from `2.8.1` to [v2.13.2](https://github.com/cypress-io/eslint-plugin-cypress/releases/tag/v2.13.2)
Using the most up-to-date version of [eslint-plugin-cypress](https://www.npmjs.com/package/eslint-plugin-cypress) helps ensure quality examples to be integrated into the Cypress product.
```bash
npm ci
npm run lint
```
=> chore(deps): update eslint-plugin-cypress to 2.13.2

README.md
This PR removes the non-working link to https://cloud.githubusercontent.com/assets/1268976/14084252/e309e370-f4e7-11e5-9562-24f516563ac9.gif which is an  outdated animated gif graphic at the top of the [README](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md) file.
The link https://cloud.githubusercontent.com/assets/1268976/14084252/e309e370-f4e7-11e5-9562-24f516563ac9.gif currently does not work. Attempting to view it, results in the message "Error 503 Backend is unhealthy". I reported this into https://github.com/orgs/community/discussions/53428, however there has been no response from GitHub so far.
Internet history shows that it was working on December 21, 2022:
https://web.archive.org/web/20221221212458/https://cloud.githubusercontent.com/assets/1268976 …
=> docs: remove outdated intro animated gif

README.md
This PR replaces the old type of Cypress Dashboard badge currently displayed in the [README](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md) file
[![Cypress Dashboard](https://img.shields.io/badge/cypress-dashboard-brightgreen.svg)](https://dashboard.cypress.io/#/projects/4b7344/runs)
using instead a Cypress Cloud badge
[![Cypress Dashboard](https://img.shields.io/endpoint?url=https://cloud.cypress.io/badge/simple/4b7344/master&style=flat&logo=cypress)](https://cloud.cypress.io/projects/4b7344/runs)
[README Badges](https://docs.cypress.io/guides/cloud/projects#README-Badges)
=> docs: migrate from Cypress Dashboard to Cloud badge

README.md
This PR adds a link to the Cypress documentation page
[CI Provider Examples](https://docs.cypress.io/guides/continuous-integration/ci-provider-examples)
where links to live CI examples from the [Real World App (RWA)](https://github.com/cypress-io/cypress-realworld-app) are listed. This expands on the examples listed in this ([cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink)) repository.
- [CircleCI](https://github.com/cypress-io/cypress-realworld-app/blob/develop/.circleci/config.yml)
- [GitHub-Action](https://github.com/cypress-io/cypress-realworld-app/blob/develop/.github/workflows/main.yml)
- [Bitbucket](https://github.com/cypress-io/cypress-realworld-app/blob/develop/bitbucket-pipelines.yml)
- …
=> docs: add link to Cypress CI documentation examples

cypress/e2e/2-advanced-examples/viewport.cy.js, cypress/e2e/2-advanced-examples/waiting.cy.js
If the eslint rule `cypress/no-unnecessary-waiting` from [eslint-plugin-cypress: Rules](https://github.com/cypress-io/eslint-plugin-cypress#rules) is enabled, then some examples from [cypress/e2e/2-advanced-examples](https://github.com/cypress-io/cypress-example-kitchensink/tree/master/cypress/e2e/2-advanced-examples) fail linting with the message:
"error  Do not wait for arbitrary time periods  cypress/no-unnecessary-waiting"
`cypress/no-unnecessary-waiting` belongs to the set of `plugin:cypress/recommended` rules as defined in [eslint-plugin-cypress: Rules](https://github.com/cypress-io/eslint-plugin-cypress#rules), so it can be expected that this set of rules is commonly applied by default.
The examples which fail this rule contains legitimate and responsible demonstrations of …
=> chore: disable eslint cypress/no-unnecessary-waiting rule checking in examples

README.md
This PR adds a `legacy` notation to each of the [README > CI Community Examples](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md#ci-community-examples) since each of these examples is outdated. They are currently displayed as:
---
CI | Url
:--- | :--- |
IBM Cloud CI | [Cloud Foundry](https://github.com/iamgollum/cypress-example-kitchensink/tree/281-ibm-cloud-pipeline)
GitLab CI | [Example caching when installing using Yarn](https://gitlab.com/bahmutov/cypress-yarn-gitlab-ci-example)
CodeFresh | [bahmutov/cypress-codefresh-example](https://github.com/bahmutov/cypress-codefresh-example)
---
[Cloud Foundry](https://github.com/iamgollum/cypress-example-kitchensink/tree/281-ibm-cloud-pipeline)
is a link to …
=> docs: add legacy to community examples

.eslintrc
This PR is an enhancement to the CI process of the repository. It adds the [eslint-plugin-cypress > Recommended configuration](https://github.com/cypress-io/eslint-plugin-cypress#recommended-configuration) to the set of rules which are checked.
The [.eslintrc](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.eslintrc) ESLint configuration file has the following configuration option added:
```json
"extends": [
"plugin:cypress/recommended"
],
```
Additionally, and pending resolution of issue https://github.com/cypress-io/cypress-example-kitchensink/issues/661, the eslint rule `cypress/unsafe-to-chain-command` from [eslint-plugin-cypress: Rules](https://github.com/cypress-io/eslint-plugin-cypress#rules) is disabled:
```json
"rules": {
"cypress/unsafe-to-chain-command": …
```
=> ci: add eslint cypress/recommended

README.md
This PR adds the example workflow [.github/workflows/using-action.yml](.github/workflows/using-action.yml) using the *Cypress.io*-provided JavaScript action for the [GitHub Actions CI/CD](https://docs.github.com/en/actions) platform:
[**cypress-io/github-action**](https://github.com/cypress-io/github-action)
to the [CI status](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md#ci-status) list in the [README](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md) document of this repository.
The action is also listed on:
- GitHub's Marketplace as [cypress-io/github-action](https://github.com/marketplace/actions/cypress-io#cypress-iogithub-action--)
- npm's JavaScript Package Registry as …
=> docs: add JavaScript cypress-io/github-action to CI status list

README.md
This PR splits the original table of CI providers into two different tables.
The first table under the heading "CI Status" gives an overview of live CI workflows.
A new second table under the heading "CI Workflow Examples" is created which holds documentation-only examples.
This makes the presentation of examples much clearer.
Additionally each of the CI Providers is linked to the documentation website of the provider for better reference to up-to-date documentation.
=> docs: split ci status examples into live and documentation-only

.circleci/config.yml, .github/workflows/using-action.yml, Jenkinsfile, azure-ci.yml, basic/.travis.yml, basic/Jenkinsfile, basic/azure-ci.yml, basic/buildspec.yml, buildspec.yml
This PR changes comments referring to the (Cypress) dashboard to refer instead to Cypress Cloud.
=> chore: rename cypress dashboard to cypress cloud

Dockerfile, basic/codeship-pro/Dockerfile
Scripts folder needed when creating a docker image with "docker build". If the folder is not copied, then "RUN npm ci" will throw the following error: 
"Error: Cannot find module '/home/node/app/scripts/prepare.js'"
=> build: add scripts to Docker build

README.md
The link to the [Cy GitHub Actions workflow (.github/workflows/using-action.yml)](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/using-action.yml) is corrected.
It was previously linking to the [Cy GitHub Actions workflow result](https://github.com/cypress-io/cypress-example-kitchensink/actions/workflows/using-action.yml) instead of directly to the workflow source file itself.
=> docs: correct gha workflow link

azure-ci.yml
Closes https://github.com/cypress-io/cypress-example-kitchensink/issues/664.
Since we do not recommend the pattern we use in the example, we should help folks find the patterns we do recommend.
I can see that the example itself makes some sense as it is, since it avoids external dependencies, so I think the example itself is OK.
=> chore: Add note to Azure example

.github/workflows/chrome-docker.yml, .github/workflows/chrome.yml, .github/workflows/using-action.yml
This PR migrates workflows in [.github/workflows](https://github.com/cypress-io/cypress-example-kitchensink/tree/master/.github/workflows)
- from `cypress-io/github-action@v5` running under `node16`
- to `cypress-io/github-action@v6` running under `node20`
Node.js `16` enters [end-of-life](https://github.com/nodejs/release#release-schedule) on Sep 11, 2023.
=> chore(deps): update to cypress-io/github-action@v6

.circleci/config.yml
chore: CircleCi Orb has been upgraded to address chrome driver download issues.
=> chore: update circleci orb to latest

.circleci/config.yml
-Closes #721
introduces the circleci windows orb, which in turn bumps node from `v14` to `v20` in windows execution environments in CI
=> chore: update windows executor

.circleci/config.yml
update circleCI macOS runner to gen2 as gen1 is being removed on October 2nd
=> chore: update xcode and resource class to gen2 macOS executor

README.md
This PR removes legacy [CI Community Examples](https://github.com/cypress-io/cypress-example-kitchensink#ci-community-examples) from the [README](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md) file.
| CI                    | Link                                                                                                     | Cypress<br>version | Last update  |
| :-------------------- | :------------------------------------------------------------------------------------------------------- | --------------- | ------------ |
| IBM Cloud CI (legacy) | [Cloud Foundry](https://github.com/iamgollum/cypress-example-kitchensink/tree/281-ibm-cloud-pipeline)    | `3.4.1`         | Aug 8, 2019  |
| GitLab CI (legacy)    | [Example caching when installing using …
=> docs: remove legacy community examples

appveyor.yml
This PR updates the [appveyor.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/appveyor.yml) CI workflow to run under the default Node.js `20` as specified in [.node-version](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.node-version)
https://github.com/cypress-io/cypress-example-kitchensink/blob/277e055329a3c1a07674aeaf42d882488dcdbb78/.node-version#L1
It also explicitly specifies to use the `Visual Studio 2022` image for clarity of the example (the default would be `Visual Studio 2015`, although this can also be overridden in the UI), see [Build worker images](https://www.appveyor.com/docs/build-environment/#build-worker-images).
The Firefox test is removed from the Appveyor CI workflow, since it has proved to be flakey in the Appyeyor …
=> ci: update appveyor to run on node.js 20

.github/workflows/chrome-docker.yml, .github/workflows/chrome.yml, .github/workflows/parallel.yml, .github/workflows/single.yml, .github/workflows/using-action.yml
This PR updates several GitHub Actions CI workflows residing in the [.github/workflows](https://github.com/cypress-io/cypress-example-kitchensink/tree/master/.github/workflows) directory to run under the default Node.js `20` version as specified in [.node-version](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.node-version)
https://github.com/cypress-io/cypress-example-kitchensink/blob/277e055329a3c1a07674aeaf42d882488dcdbb78/.node-version#L1
All usage of [actions/checkout](https://github.com/actions/checkout) is migrated from `v3` to `v4`.
- `actions/checkout@v3` runs under `node16`
- `actions/checkout@v4` runs under `node20`
The Docker image [cypress/browsers](https://hub.docker.com/r/cypress/browsers/) is changed from
- `cypress/browsers:node18.12.0-chrome107` …
=> ci: update GitHub Actions workflows to run on node.js 20

.travis.yml, basic/.travis.yml
This PR removes the Ubuntu/Debian package `libgconf-2-4` from the documentation-only example workflows
- [.travis.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.travis.yml)
- [basic/.travis.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/basic/.travis.yml)
The Cypress documentation [Getting Started > Installating Cypress > System requirements > Linux Prerequisites > Ubuntu/Debian](https://docs.cypress.io/guides/getting-started/installing-cypress#UbuntuDebian) no longer lists `libgconf-2-4` as a prerequisite.
- The legacy [Cypress version 3.4.1](https://docs.cypress.io/guides/references/changelog#3-4-1) was the last version to require `libgconf-2-4` (Cypress binary depends on `libgconf-2.so.4`). This version of Cypress was released on …
=> ci: remove libgconf-2-4 from travis-ci workflows

.circleci/config.yml, .github/workflows/chrome-docker.yml, .github/workflows/parallel.yml, .github/workflows/single.yml, .gitlab-ci.yml, .semaphore/semaphore.yml, .travis.yml, Dockerfile, Jenkinsfile, azure-ci.yml, basic/.circleci/config.yml, basic/.gitlab-ci.yml, basic/.semaphore.yml, basic/.travis.yml, basic/Jenkinsfile, basic/azure-ci.yml, basic/buildspec.yml, basic/codeship-pro/Dockerfile, buddy.yml
This PR updates CI workflows to use Node.js `20.x`, codename 'Iron'.
[Node.js v20.9.0](https://nodejs.org/en/blog/release/v20.9.0) became the Active LTS version on Oct 24, 2023.
Docker images are transitioned to:
- [cypress/base](https://hub.docker.com/r/cypress/base)
`cypress/base:20.9.0`
- [cypress/browsers](https://hub.docker.com/r/cypress/browsers/)
`cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1`
GitHub actions are updated to use [actions/setup-node@v4](https://github.com/actions/setup-node), which is the version compatible with `node20`.
Node.js transitioned version `18.x` to LTS maintenance status and version `20.x` to active LTS status on October 24, 2023 (see [Node.js release schedule](https://github.com/nodejs/release#release-schedule) and …
=> ci: update workflows to use Node.js 20.x LTS

.circleci/config.yml, package-lock.json, package.json, scripts/test-execa.js
- Close https://github.com/cypress-io/cypress-example-kitchensink/pull/773
Execa isn't used - it's referenced in commented out code in Circle.yml for debugging purposes (I suppose?) Removing the dep so we don't have to keep up with dep and dep updates.
colon-names is just not really a necessary dep. If enforces npm script formatting.
=> chore: remove unused/unnecessary deps

.github/workflows/using-action.yml
This PR changes the GitHub Actions matrix variable name from `machines` to `containers` in the workflow [using-action.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/using-action.yml) for consistency with the [Cypress documentation (docs.cypress.io)](https://docs.cypress.io/) and the [Cypress GitHub Action repo (github.com/cypress-io/github-action)](https://github.com/cypress-io/github-action). It also expands on the in-line explanation about the matrix array `containers`.
Although the workflow previously explained that the items in the matrix did not matter, it has led to some confusion in new users concerning the matrix variable name `machines` used by the example GitHub Action workflow …
=> ci: use containers matrix name in github actions workflow

.github/workflows/parallel.yml, .github/workflows/single.yml
- This PR follows on from https://github.com/cypress-io/cypress-example-kitchensink/pull/752 and updates the GitHub-provided JavaScript [actions/cache](https://github.com/actions/cache) to `v4` for compatibility with `node20`.
The following workflows output a deprecation warning when run on GitHub:
- [single.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/single.yml)
- [parallel.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/parallel.yml)
Deprecation warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-1 …
=> ci(deps): update actions/cache to v4

README.md, app/index.html, package.json
- closes #796
The repo description does not take account of the addition of Component Testing to the previously available End-to-End Testing. `cypress-example-kitchensink` provides for E2E Testing only, not Component Testing.
The repo also claims that "every API command in Cypress" is tested, which is not completely true.
The following locations are updated:
- [README](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md)
- [package.json](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/package.json)
- [app/index.html](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/app/index.html)
1. The testing is qualified as "Cypress.io End-to-End (E2E) testing"
2. A link to …
=> fix: qualify E2E testing scope

.eslintrc, cypress/e2e/2-advanced-examples/actions.cy.js, cypress/e2e/2-advanced-examples/cookies.cy.js, cypress/e2e/2-advanced-examples/misc.cy.js, cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js, cypress/e2e/2-advanced-examples/storage.cy.js, cypress/e2e/2-advanced-examples/utilities.cy.js
=> fix: lint errors

app/commands/actions.html, app/commands/cookies.html, app/commands/misc.html, app/commands/spies-stubs-clocks.html, app/commands/storage.html, app/index.html, app/utilities.html, cypress/e2e/2-advanced-examples/cookies.cy.js, cypress/e2e/2-advanced-examples/misc.cy.js
=> fix: update example docs to match tests

package-lock.json
`npm audit` shows a vulnerability from `follow-redirects@1.15.5`
```test
follow-redirects  <=1.15.5
Severity: moderate
follow-redirects' Proxy-Authorization header kept across hosts - https://github.com/advisories/GHSA-cxjh-pqwp-8mfp
fix available via `npm audit fix`
node_modules/follow-redirects
```
`follow-redirects` is a dependency of `start-server-and-test`
```text
└─┬ start-server-and-test@2.0.3
└─┬ wait-on@7.2.0
└─┬ axios@1.6.7
└── follow-redirects@1.15.5
```
`start-server-and-test@2.0.3` is uninstalled and reinstalled with npm.
```shell
npm uninstall start-server-and-test
npm install start-server-and-test -D -E
```
This refreshes dependencies `axios` and `follow-redirects`, remediating the moderate vulnerability from `follow-redirects@1.15.5` by updating to …
=> chore(deps): refresh start-server-and-test

.circleci/config.yml, package-lock.json, package.json
`npm audit` reports vulnerabilities. The following vulnerabilities come from the use of [semantic-release@19.0.5](https://github.com/semantic-release/semantic-release/releases/tag/v19.0.5)
- ip  2.0.0 Severity: moderate
- semver  7.0.0 - 7.5.1 npm Severity: moderate
`npm audit fix` reports that these vulnerabilities cannot be fixed automatically.
The currently used version, [semantic-release@19.0.5](https://github.com/semantic-release/semantic-release/releases/tag/v19.0.5), was released in Aug 2022.
Update to [semantic-release@21.1.2](https://github.com/semantic-release/semantic-release/releases/tag/v21.1.2). This version has proved stable in the [cypress-io/github-action](https://github.com/cypress-io/github-action) where it is called through …
=> fix: update semantic-release to 21.1.2

app/commands/misc.html
Closes #819
Re-adds the `end()` table code so older versions of cypress with the scaffolded `misc()` tests continue to work
=> fix: readd end table for older versions of cypress

.eslintrc
[eslint-plugin-mocha](https://www.npmjs.com/package/eslint-plugin-mocha) is configured inconsistently in this repo regarding the rules:
- [mocha/no-exclusive-tests](https://github.com/lo1tuma/eslint-plugin-mocha/blob/main/docs/rules/no-exclusive-tests.md) to warn about the use of  `describe.only`, `it.only`, etc. - configured to `error`
- [mocha/no-skipped-tests](https://github.com/lo1tuma/eslint-plugin-mocha/blob/main/docs/rules/no-skipped-tests.md) to warn about the use of `describe.skip`, `it.skip`, etc. - configured per `plugin:mocha/recommended` for `warn` only (see [Rules table](https://github.com/lo1tuma/eslint-plugin-mocha/blob/main/README.md#rules)) for this plugin.
Since it is undesirable to have `.only` or `.skip` in the example test specs, both should be configured to `error` …
=> ci: cause skipped tests linting error

.circleci/config.yml
Brownout today that highlighted the deprecated resource class is in use: https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718
=> chore: bump CircleCI resource class from intel to m1

package-lock.json, package.json
Starting the server, logs the following information:
```text
cypress-example-kitchensink@0.0.0-development start
> node ./scripts/start.js
Running "serve --listen 8080 --no-request-logging --no-clipboard"...
UPDATE  The latest version of `serve` is 14.2.2
```
Bumps the version of npm module [serve](https://www.npmjs.com/package/serve) from `14.2.1` to [14.2.2](https://github.com/vercel/serve/releases/tag/14.2.2) (latest).
Ubuntu `22.04.4` LTS, Node.js `20.12.2`
```bash
npm ci
npm run local:run
```
1. The tests should be successful.
1. The information text "UPDATE AVAILABLE The latest version of `serve` is 14.2.2" should **not** appear.
=> chore(deps): update serve to 14.2.2

.eslintrc, package-lock.json, package.json
The ESLint rule [indent](https://eslint.org/docs/latest/rules/indent) was **deprecated** in ESLint `v8.53.0`. The ESlint documentation suggests to use the [corresponding rule](https://eslint.style/rules/js/indent) in [`@stylistic/eslint-plugin-js`](https://eslint.style/packages/js).
This repo uses ESLint `v8.57.0` and so the deprecation already applies.
1. The npm module [@stylistic/eslint-plugin-js](https://www.npmjs.com/package/@stylistic/eslint-plugin-js) is added using the release [@stylistic/eslint-plugin-js@1.7.2](https://github.com/eslint-community/eslint-stylistic/releases/tag/v1.7.2).
2. The [.eslintrc](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.eslintrc) configuration is changed:
1. `@stylistic/js` added to `plugins`
2. The `indent` rule is changed …
=> chore(deps): migrate to eslint stylistic 1.7.2

.eslintrc, package-lock.json, package.json
- The current linting setup does not catch any `json` errors in the examples.
- [eslint-plugin-json-format](https://www.npmjs.com/package/eslint-plugin-json-format) is installed, however it is not configured in [.eslintrc](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.eslintrc) to be active in terms of the plugin itself, nor the filename extension `*.json`.
Ubuntu `22.04.4` LTS, Node.js `20.12.2` LTS
Execute
```shell
git clone https://github.com/cypress-io/cypress-example-kitchensink
cd cypress-example-kitchensink
npm ci
npm run lint
```
and confirm that no errors are reported.
Now temporarily delete the end-of-line commas in [cypress/fixtures/example.json](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/cypress/fixtures/example.json) and …
=> test: replace and activate json linting

cypress/e2e/2-advanced-examples/connectors.cy.js, cypress/e2e/2-advanced-examples/cypress_api.cy.js, cypress/e2e/2-advanced-examples/navigation.cy.js, cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js
ESLint `9.x` identifies usages in the repo of unnecessary ESLint rule disables.
This affects the following instances:
`/* eslint-disable-next-line no-console */` in
- [cypress/e2e/2-advanced-examples/connectors.cy.js](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/cypress/e2e/2-advanced-examples/connectors.cy.js)
- [cypress/e2e/2-advanced-examples/cypress_api.cy.js](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/cypress/e2e/2-advanced-examples/cypress_api.cy.js)
- [cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js)
The ESLint [no-console](https://eslint.org/docs/latest/rules/no-console) rule does not belong to …
=> fix: clean unused eslint disables

eslint.config.mjs
[eslint.config.mjs](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/eslint.config.mjs) relies on using `import { FlatCompat } from '@eslint/eslintrc'` to run `eslint-plugin-cypress`.
Starting with [eslint-plugin-cypress@3.3.0](https://www.npmjs.com/package/eslint-plugin-cypress/v/3.3.0) the plugin has full support for Flat config files using:
```js
import pluginCypress from 'eslint-plugin-cypress/flat'
export default [
pluginCypress.configs.recommended
]
```
1. Remove `@eslint/eslintrc`
2. Add `eslint-plugin-cypress/flat`
```shell
npm ci
npm run lint
```
=> test: convert to ESLint Flat config

package-lock.json, package.json
- PR #845 removed the use of `@eslint/eslintrc`. It is still explicitly listed in `package.json`, which is unnecessary.
Uninstall `@eslint/eslintrc`. Note that it remains in `package-lock.json` since it is also a dependency of [eslint](https://www.npmjs.com/package/eslint).
```shell
npm ci
npm run lint
```
=> chore(deps): remove @eslint/eslintrc

.circleci/config.yml, .github/workflows/chrome-docker.yml, .gitlab-ci.yml, Dockerfile, Jenkinsfile, basic/.circleci/config.yml, basic/.gitlab-ci.yml, basic/Jenkinsfile, basic/codeship-pro/Dockerfile, buddy.yml
Multiple example workflows use outdated Cypress Docker images.
Update to
- [cypress/base:20.14.0](https://hub.docker.com/layers/cypress/base/20.14.0/images/sha256-2314cbaca5d133d2c69f91cec9f6b6f1787b32ea2dc7c23c73bd817e0f8f4316)
- [cypress/browsers:node-20.14.0-chrome-126.0.6478.114-1-ff-127.0.1-edge-126.0.2592.61-1](https://hub.docker.com/layers/cypress/browsers/node-20.14.0-chrome-126.0.6478.114-1-ff-127.0.1-edge-126.0.2592.61-1/images/sha256-2d861960dadb4fe650d99bad6fca692cd61982ac584983a1af4de7c42ef595c1)
=> test(deps): update docker image versions to node-20.14.0

.circleci/config.yml, package-lock.json, package.json
`npm audit` reports 5 vulnerabilities (4 moderate, 1 high) due to `semantic-release@21.1.2`
[semantic-release@22.0.0](https://github.com/semantic-release/semantic-release/releases/tag/v22.0.0) requires Node.js >= v20.6.0
[semantic-release@23.0.0](https://github.com/semantic-release/semantic-release/releases/tag/v23.0.0) requires Node.js >= v20.8.1
[semantic-release@24.0.0](https://github.com/semantic-release/semantic-release/releases/tag/v24.0.0) has no change for Node.js, however it is currently using beta dependencies
Update `package.json` to [semantic-release@23.1.1](https://github.com/semantic-release/semantic-release/releases/tag/v23.1.1)
Run `npm audit fix` after update.
Update the `release` job in [.circleci/config.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/ …
=> feat(deps): update semantic-release to 23.1.1

package.json
npm reports in workflow log
https://app.circleci.com/pipelines/github/cypress-io/cypress-example-kitchensink/1886/workflows/55d7c8d6-7241-4bc9-8691-d5deb7dc8b41/jobs/12980?invite=true#step-102-6007_121
> npm warn publish npm auto-corrected some errors in your package.json when publishing.  Please run "npm pkg fix" to address these errors.
> npm warn publish errors corrected:
> npm warn publish "repository.url" was normalized to "git+https://github.com/cypress-io/cypress-example-kitchensink.git"
Currently https://github.com/cypress-io/cypress-example-kitchensink/blob/b2c085df9aff01419963e9101969b87176eaa78c/package.json#L48-L51 defines the repository using the `https` protocol.
Permanently normalize the repo reference in `package.json` using `npm pkg fix` to change to `git+https` protocol: …
=> chore: normalize package.json repository protocol definition

.circleci/config.yml
- closes https://github.com/cypress-io/cypress-example-kitchensink/issues/857
The [.circleci/config.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.circleci/config.yml) workflow shows multiple `EBADENGINE` warnings.
The `linux-build` jobs in the `workflows` section are currently running under the Node.js default `v18.16.1` from the Cypress CircleCI Orb. They need to run under Node.js `20.x` to be compatible with currently configured dependencies.
- Move the `linux-build` jobs in the `workflows` section to the `jobs` section
- Convert the jobs from using the Cypress Circle CI Orb job [cypress/run](https://circleci.com/developer/orbs/orb/cypress-io/cypress#jobs-run) to use instead the Cypress Circle CI Orb command …
=> ci: convert linux tests for Node.js 20

.circleci/config.yml
- https://github.com/cypress-io/cypress-example-kitchensink/pull/859 introduced a grouping error for Firefox parallel tests in the [.circleci/config.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.circleci/config.yml) workflow. The Firefox tests are incorrectly grouped into `2x-chrome on CircleCI` which causes grouping to fail due to mismatched browsers.
This can cause either the `linux-test-chrome` or `linux-test-firefox` job to fail, depending on timing. The failure also prevents the `release` job running.
Due to the PRs coming from a fork, recording is not tested until the PR is merged since Cypress Cloud project Id and record key are secrets.
See https://app.circleci.com/pipelines/github/cypress-io/cypress-example-kitchensink/1898/workflows/a8f38ed8-12fc-4b5 …
=> ci: fix firefox group recording

README.md
In the [README](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md#help--testing) the goals are:
- simplification for first-time users
- more clarity in the documentation between local / CI testing, usage and support
- preparation to add information about running Docker, so that the structures will be able to fit. (The plan is to mark the CI examples which use Docker and add explicit instructions about running the repo in Docker locally.)
This PR restructures the [README](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md#help--testing) section about running tests.
It starts from a set of instructions to clone and run, which can be simply copied and pasted. It explains then in more detail about options and what happens behind the …
=> docs: restructure run tests documentation

README.md
There are issues with the documentation of the following GitHub Actions workflows in the [README](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md)
- [.github/workflows/single.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/single.yml) is incorrectly categorized as "documentation-only" whereas it is live and records to Cypress Cloud
- [.github/workflows/chrome.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/chrome.yml) is not listed. It is live and does not record.
- [.github/workflows/chrome-docker.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/chrome-docker.yml) is not listed. It is live and does not record.
In the …
=> docs: fix GitHub actions workflow listings

README.md
Although there is usage of [Cypress Docker images](https://github.com/cypress-io/cypress-docker-images) in CI in this repo, the examples are not explicitly called out, so are less easy to find.
- CircleCI (basic + full parallel)
- Buddy.works (basic)
- CloudBees CodeShip Pro (basic + full parallel)
- GitHub Actions (chrome-docker)
- GitLab (basic + full parallel)
- Jenkins (basic + full parallel)
Add text to the [README](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md) document and modify the tables to show where [Cypress Docker images](https://github.com/cypress-io/cypress-docker-images) are used.
=> docs: show Docker examples in tables

README.md
There are no examples of running Cypress tests from this repository interactively with Cypress Docker images.
Add examples of using the repository interactively with Cypress Docker images for
- `cypress/base`
- `cypress/browsers`
- `cypress/included`
=> docs: add interactive Docker examples

.github/workflows/chrome.yml, .github/workflows/parallel.yml, .github/workflows/single.yml
The following workflow running in GitHub Actions shows a warning message: `npm warn EBADENGINE Unsupported engine`:
- [.github/workflows/chrome.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/chrome.yml)
This workflow, running in GitHub Actions [ubuntu-22.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md), uses the default Node.js `18.20.4` and not Node.js `20` as specified in [.node-version](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.node-version). 
- Due to PR https://github.com/cypress-io/cypress-example-kitchensink/pull/849, a minimum Node.js `v20.8.1` is required.
Add [actions/setup-node](https://github.com/actions/setup-node) using `node-version-file` set to …
=> ci: use .node-version file for GitHub Actions setup

package-lock.json
Dependabot reports alert [Server-Side Request Forgery in axios](https://github.com/advisories/GHSA-8hc4-vh64-cxmj) for [package-lock.json](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/package-lock.json).
[axios](https://www.npmjs.com/package/axios) is a transient dependency of
https://github.com/cypress-io/cypress-example-kitchensink/blob/db9556cb3fe7e4236d2903023c18c12eb22caa94/package-lock.json#L26
Resolve the vulnerability with `npm audit fix` which updates `axios` to `1.7.4`.
- See https://github.com/jeffbski/wait-on/issues/159
=> chore(deps): update axios to 1.7.4

.github/workflows/chrome-docker.yml, .github/workflows/chrome.yml, .github/workflows/parallel.yml, .github/workflows/single.yml, .github/workflows/using-action.yml
The GitHub runner image [ubuntu-24.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md) is replacing [ubuntu-22.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md) as `latest` image.
Migrate GitHub Actions workflows to [ubuntu-24.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md).
Affected workflows:
- [.github/workflows/chrome-docker.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/chrome-docker.yml)
- [.github/workflows/chrome.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/chrome.yml)
- [.github/workflows/parallel.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/mas …
=> ci: migrate github action workflows to ubuntu-24.04

package-lock.json, package.json
ESLint-related dependencies are out of date. Particularly `eslint-plugin-cypress` should be showcasing the latest version `4.0.0`.
- Update [@stylistic/eslint-plugin-js](https://www.npmjs.com/package/@stylistic/eslint-plugin-js) from `2.6.5` to [2.9.0](https://github.com/eslint-stylistic/eslint-stylistic/releases/tag/v2.9.0)
- Update [eslint](https://www.npmjs.com/package/eslint) from `9.9.1` to [9.12.0](https://github.com/eslint/eslint/releases/tag/v9.12.0)
- Update [eslint-plugin-cypress](https://www.npmjs.com/package/eslint-plugin-cypress) from `3.5.0` to [4.0.0](https://github.com/cypress-io/eslint-plugin-cypress/releases/tag/v4.0.0)
```shell
npm run lint
```
=> chore(deps): update eslint* dependencies

package-lock.json, package.json
The currently configured [semantic-release@23.1.1](https://github.com/semantic-release/semantic-release/releases/tag/v23.1.1) displays a deprecation warning when installed:
> npm warn deprecated read-pkg-up@11.0.0: Renamed to read-package-up
Update to [semantic-release@24.1.3](https://github.com/semantic-release/semantic-release/releases/tag/v24.1.3)
Run `npm audit fix` due to `micromatch@4.0.5` vulnerability to update to `micromatch@4.0.8`.
=> chore(deps): update semantic release to 24.1.3

appveyor.yml
The [AppVeyor](https://ci.appveyor.com/project/cypress-io/cypress-example-kitchensink?fullLog=true) workflow, which runs CI under Windows, logs multiple deprecation messages, including:
```text
npm i -g @cypress/commit-message-install @bahmutov/print-env
npm warn deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm warn deprecated @octokit/app@2.2.2: '@octokit/app' will be repurposed in future. Use '@octokit/auth-app' instead
```
```text
commit-message-install --else "npm ci"
(node:3700) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use …
```
=> ci: remove use of @cypress/commit-message-install

package-lock.json, package.json
This repo is currently configured for [npm-run-all2@^5.0.0](https://github.com/bcomnes/npm-run-all2) and is locked to [npm-run-all2@5.0.2](https://github.com/bcomnes/npm-run-all2/releases/tag/v5.0.2), released December 2020.
[npm-run-all2@7.0.1](https://github.com/bcomnes/npm-run-all2/releases/tag/v7.0.1) is the `latest` release dated October 2024.
Update from [npm-run-all2@^5.0.0](https://github.com/bcomnes/npm-run-all2) to [npm-run-all2@7.0.1](https://github.com/bcomnes/npm-run-all2/releases/tag/v7.0.1).
(Note that [.npmrc](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.npmrc) includes `save-exact=true`.)
This is a routine maintenance update to pull in fixes from the last 4 years.
```shell
npm ci
npm run test:ci
```
=> fix(deps): update npm-run-all2 to 7.0.1

README.md
1. The [GitHub Markdown extension: Alert](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) `[!NOTE]` is rendered literally in the [README](https://www.npmjs.com/package/cypress-example-kitchensink?activeTab=readme) as displayed on the [npm registry](https://www.npmjs.com/package/cypress-example-kitchensink) instead of being interpreted.
2. Use of Docker working directory `/e2e` has been changed to the neutral `/app` directory in the examples in the https://github.com/cypress-io/cypress-docker-images repo.
3. The bookmark https://github.com/cypress-io/cypress-docker-images/blob/master/README.md#tag-selection was changed to `#tags`
1. Replace `[!NOTE]` with the simple text `NOTE:` so …
=> docs: update README Docker section

basic/buildspec.yml, buildspec.yml
When the main branch has advanced compared to the currently checked out commit,`git name-rev` will print e.g. `main~3`.
To keep Cypress branch names clean, we want `COMMIT_INFO_BRANCH` to be just `main`, though.
Therefore, I suggest cutting off the suffix.
---
If this gets merged, I believe the docs have to be afterwards updated in multiple places, too, e.g. here: https://github.com/cypress-io/cypress-documentation/blob/main/docs/app/continuous-integration/aws-codebuild.mdx
I could do that, too, if desired, but of course don't have an overview of _all_ the correct places.
=> docs: AWS codebuild: Avoid branch names like `main~3`.

cypress/support/e2e.js
[cypress/support/e2e.js](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/cypress/support/e2e.js) no longer corresponds to the default scaffolded file contents.
Cypress dynamically builds support files when scaffolding based on the texts in https://github.com/cypress-io/cypress/blob/develop/packages/scaffold-config/src/supportFile.ts. For E2E tests the text is:
```js
// ***********************************************************
// This example support/e2e.${language} is processed and
// loaded automatically before your test files.
//
// This is a great place to put global configuration and
// behavior that modifies Cypress.
//
// You can change the location of this file or turn off
// automatically serving support files with the
// 'supportFile' configuration option. …
```
=> chore: remove CommonJS comment from cypress/support/e2e.js

.github/workflows/using-action.yml
The workflow [.github/workflows/using-action.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/using-action.yml) runs using the GitHub Actions runner default Node.js version `18.20.7` in [windows-latest / windows-2022](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md). This is not compatible with the configured [semantic-release@24.1.3](https://github.com/semantic-release/semantic-release/releases/tag/v24.1.3), which requires Node.js >= `20.8.1`.
The job `parallel-runs-across-platforms` displays a warning in the step `run tests`:
> npm warn EBADENGINE Unsupported engine
Add the following to each job in the workflow [.github/workflows/using-action.yml](https://github.com/cypress-io/cypress-example-kitchensink/ …
=> test: add setup-node to using-action workflow

.circleci/config.yml
- closes https://github.com/cypress-io/cypress-example-kitchensink/issues/938
Currently the CI pipeline [.circleci/config.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.circleci/config.yml) workflow `win-build` runs using the default Node.js version `v21.7.3` of the CircleCI [windows-orb@5.0.0](https://github.com/CircleCI-Public/windows-orb/releases/tag/v5.0.0).
Node.js version `v21.7.3` is however no longer supported by [Node.js](https://github.com/nodejs/release#release-schedule), nor by [Cypress](https://docs.cypress.io/app/get-started/install-cypress#Nodejs). It reached its [end-of-life milestone](https://github.com/nodejs/release#release-schedule) on June 1, 2024 already.
1. Update from [windows-orb@5.0.0](https://github.com/CircleCI-Public/windows-orb/rel …
=> ci: use node.js 22 in circleci windows jobs

.circleci/config.yml
- closes https://github.com/cypress-io/cypress-example-kitchensink/issues/940
The CI pipeline [.circleci/config.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.circleci/config.yml) workflow `mac-build` runs in Node.js `v20.13.1`.
It should run in the Node.js version specified in [.node-version](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.node-version), which is currently `22`.
1. Update to executor [xcode@16.2.0](https://circle-macos-docs.s3.amazonaws.com/image-manifest/v15180/manifest.txt)
2. Use [nvm](https://github.com/nvm-sh/nvm) to install Node.js `22` in the CI pipeline [.circleci/config.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.circleci/config.yml) workflow `mac-build` job `mac-test`
This …
=> ci: use node.js 22 in circleci mac job

.circleci/config.yml
The `browsers` executor in the pipeline [.circleci/config.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.circleci/config.ym) is unused code:
https://github.com/cypress-io/cypress-example-kitchensink/blob/8d10f646e2aa35731f10bbe4e3e265bdf7b5001e/.circleci/config.yml#L19-L21
- This has been the case since PR #591 in March 2023. Browsers are provided through the `cypress-io/cypress@3` Orb.
Remove the dead code `browsers` executor from the pipeline [.circleci/config.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.circleci/config.ym).
=> ci: remove unused browsers executor

package-lock.json, package.json
`npm audit` reports a high severity vulnerability [CVE-2025-27152](https://github.com/advisories/GHSA-jr5f-v2jv-69x6) due to
`axios  <1.8.2` as transient dependency:
```text
└─┬ start-server-and-test@2.0.9
└─┬ wait-on@8.0.1
└── axios@1.7.9
```
Update from [start-server-and-test@2.0.9](https://github.com/bahmutov/start-server-and-test/releases/tag/v2.0.9) to [start-server-and-test@2.0.11](https://github.com/bahmutov/start-server-and-test/releases/tag/v2.0.11)
```text
└─┬ start-server-and-test@2.0.11
└─┬ wait-on@8.0.3
└── axios@1.8.4
```
=> chore(deps): update start-server-and-test to 2.0.11

.circleci/config.yml, .github/workflows/chrome-docker.yml, .gitlab-ci.yml, .semaphore/semaphore.yml, .travis.yml, Dockerfile, Jenkinsfile, basic/.circleci/config.yml, basic/.gitlab-ci.yml, basic/.semaphore.yml, basic/.travis.yml, basic/Jenkinsfile, basic/buildspec.yml, basic/codeship-pro/Dockerfile, buddy.yml, buildspec.yml
Example workflows are using inconsistent versions of Node.js:
- `20`
- `22.11.0`
- `22.14.0`
- `latest`
This was partially caused by Renovate PR https://github.com/cypress-io/cypress-example-kitchensink/pull/951 updating some Cypress Docker usage from `cypress/base:22.11.0` to `cypress/base:22.14.0`, leaving other instances still using `cypress/base:22.11.0` or directly using Node.js `22.11.0`.
Update Node.js usage to latest [Active LTS version](https://nodejs.org/en/about/previous-releases):
- Cypress Docker images to  `cypress/base:22.15.0`
- other Node.js versions to `22.15.0` or generic `22`
=> chore(deps): update ci examples to node 22.15.0

eslint.config.mjs, scripts/set-port.js, scripts/start.js
The repo already uses [@stylistic/eslint-plugin](https://eslint.style/) to lint styling in the repo according to the configuration in [eslint.config.mjs](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/eslint.config.mjs) which specifies:
```js
plugins: {
'@stylistic': stylistic,
},
rules: {
'@stylistic/indent': ['error', 2, { 'SwitchCase': 1, 'MemberExpression': 'off' }],
},
```
and therefore only uses one `@stylistic/eslint-plugin` rule.
The use of JavaScript `comma-dangle`, `quotes` and `semi` is left undefined.
Other repos:
- https://github.com/cypress-io/cypress-docker-images in [eslint.config.mjs](https://github.com/cypress-io/cypress-docker-images/blob/master/eslint.config.mjs)
- https://github.com/cypress-io/github-action in …
=> test: add stylistic rules (comma-dangle, quotes and semi)

app/commands/waiting.html, app/commands/window.html
Two of the app source documents contain syntax errors with stray end tags:
| Source                                                                                                                       | Destination                                 |
| ---------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------- |
| [app/commands/waiting.html](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/app/commands/waiting.html) | https://example.cypress.io/commands/waiting |
| [app/commands/window.html](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/app/commands/window.html)   | https://example.cypress.io/commands/window  |
```text …
```
=> fix: app html stray end tag syntax errors

README.md
- The Renovate badge in the [README](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md) document links to a non-existent domain `https://renovateapp.com/`.
Clicking on the badge results in a browser error. In Google Chrome "This site can’t be reached" `DNS_PROBE_FINISHED_NXDOMAIN`.
[![renovate-app badge][renovate-badge]][renovate-app]
[renovate-badge]: https://img.shields.io/badge/renovate-app-blue.svg
[renovate-app]: https://renovateapp.com/
Replace the current Renovate badge using the one from the [renovate > readme.md](https://github.com/renovatebot/renovate/blob/main/readme.md)
```markdown
[![Renovate enabled](https://img.shields.io/badge/renovate-enabled-brightgreen.svg?logo=renovatebot)](https://renovatebot.com/)
```
[![Renovate …
=> docs: update renovate badge

app/commands/actions.html, app/commands/misc.html, app/commands/storage.html, cypress.config.js, cypress/e2e/2-advanced-examples/actions.cy.js, cypress/e2e/2-advanced-examples/cypress_api.cy.js, cypress/e2e/2-advanced-examples/misc.cy.js, cypress/e2e/2-advanced-examples/storage.cy.js, eslint.config.mjs, scripts/set-port.js
Examples are currently stylistically linted according to [@stylistic/eslint-plugin](https://eslint.style/) to lint styling in the repo according to the configuration in [eslint.config.mjs](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/eslint.config.mjs) which specifies:
```js
plugins: {
'@stylistic': stylistic,
},
rules: {
'@stylistic/indent': ['error', 2, { 'SwitchCase': 1, 'MemberExpression': 'off' }],
'@stylistic/comma-dangle': ['error', 'always-multiline'],
'@stylistic/quotes': ['error', 'single'],
'@stylistic/semi': ['error', 'never'],
```
The rules marked as Recommended in [eslint-plugin/rules.md](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/packages/eslint-plugin/rules.md) are not applied as a group.
- Apply rule configuration …
=> feat: apply stylistic recommended rules to examples

app/commands/assertions.html, app/commands/spies-stubs-clocks.html
Links on web pages sourced from this repo cause HTTP 404 not found errors:
| Page                                                   | Link                                         | Error |
| ------------------------------------------------------ | -------------------------------------------- | ----- |
| https://example.cypress.io/commands/spies-stubs-clocks | https://example.cypress.io/commands/fixtures | 404   |
| https://example.cypress.io/commands/assertions         | https://on.cypress.io/using-cypress-faq      | 404   |
| Published page                                         | Source                                                                                                                                             | Original Link                                | New Link …
=> fix(docs): correct dead links in commands pages
